# Generated by Django 4.1.3 on 2022-11-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='forth',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='second',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='third',
            field=models.ImageField(default='', upload_to='profile_images'),
        ),
    ]
